jwt:
  secret: "secret"

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todoList
    username: MihkelVaino
    password: Mysqliparool1
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true